test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# amazon:
#   service: S3
#   access_key_id: YOUR_ACCESS_KEY_ID
#   secret_access_key: YOUR_SECRET_ACCESS_KEY
#   region: us-east-1
#   bucket: your_own_bucket

# google:
#   service: GCS
#   project: your_project
#   credentials: /path/to/gcs.keyfile
#   bucket: your_own_bucket

# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: YOUR_STORAGE_ACCESS_KEY
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
